loadTimeData.data = {
  bestScore: "最佳 $1 $2 $3",
  bestScoreFlyout: "最佳成绩: $1",
  bestScoreMenuDisplay: "$1 $2",
  cancel: "取消",
  close: "关闭",
  code: "作弊码已激活！",
  codeCheat: "已激活作弊代码! $1",
  codeScoring: "此轮计分已关闭。",
  endlessBestScore: -1,
  endlessDescriptor: "距离",
  endlessModeTitleInline: "无尽模式:",
  endlessTitle: "无尽模式",
  endlessUnit: "m",
  fontfamily: "system-ui, sans-serif",
  fontsize: "75%",
  gameCreditsButton: "游戏制作人员名单",
  gameCreditsDialogTitle: "游戏制作人员名单",
  gameMode: "游戏模式切换为 $1",
  gameModeSelectLabel: "游戏模式",
  gameModeSelectLabelDisabled: "游戏模式 （点击开始新游戏后可切换）",
  gameSettings: "游戏设置",
  highVisibilityActive: false,
  highVisiblityModeToggleLabel: "高可视度",
  howToPlayButton: "怎么玩",
  howToPlayControllerBoost: "按 RT 使用速度提升",
  howToPlayControllerMovement: "使用摇杆或方向键进行转向",
  howToPlayControllerRefresh: "按 LB+RB 重新启动游戏",
  howToPlayDialogTitle: "怎么玩",
  howToPlayEndless:
    "尽可能远地冲，营救朋友以帮助对付敌人",
  howToPlayKeyboardBoost: "按“F”使用速度提升",
  howToPlayKeyboardMovement: "使用箭头或“WASD”键进行转向",
  howToPlayKeyboardRefresh: "刷新页面以重新启动游戏",
  howToPlayMouseBoost: "右键单击以使用速度提升",
  howToPlayMouseMovement: "移动鼠标进行转向",
  howToPlayMouseRefresh: "刷新页面以重新启动游戏",
  howToPlayTimeTrial:
    "尽快到达终点并收集硬币以减去时间",
  howToPlayTouchBoost: "向下滑动两次以使用速度提升",
  howToPlayTouchMovement: "滑动或点击以转向",
  howToPlayTouchRefresh: "刷新页面以重新启动游戏",
  howToPlayZigZag: "连续通过尽可能多的大门",
  is_windows_xbox_sku: "false",
  keyboardAction: "空格键",
  language: "zh",
  lastSelectedMode: "endless",
  lastSelectedPlayer: 4,
  lastSelectedTheme: "surf",
  menuInfo: "开始游戏",
  mouseAction: "双击",
  newBestScore: "新最佳成绩 $1 $2 $3",
  newGame: "开始新游戏",
  off: "关",
  on: "开",
  overInfo: "再玩一次",
  overTitle: "游戏结束",
  pauseInfo: "继续游戏",
  pauseTitle: "已暂停",
  reducedSpeedActive: false,
  reducedSpeedModeToggleLabel: "降低速度",
  resetAllStats: "重置所有统计信息",
  resetAllStatsDialogText:
    "是否确实要重置所有游戏统计信息(包括高分)?",
  resetAllStatsDialogTitle: "重置所有统计数据",
  share: "与好友共享",
  shareCopy: "复制链接",
  shareLink: window.location.href,
  shareLinkCopied: "已复制链接!",
  skiTheme: "一起来滑雪吧",
  specialThanks: "特别感谢:",
  surfTheme: "让我们网上冲浪吧",
  textdirection: "ltr",
  theme: "主题切换为 $1",
  themeSelectLabel: "主题",
  timetrialBestScore: -1,
  timetrialDescriptor: "时间",
  timetrialModeTitleInline: "计时赛:",
  timetrialTitle: "计时赛",
  timetrialUnit: "s",
  touchAction: "双击",
  zigzagBestScore: -1,
  zigzagDescriptor: "通过",
  zigzagModeTitleInline: "障碍赛:",
  zigzagTitle: "障碍赛",
  zigzagUnit: "个入口",
};
